version: '3.9'

services:
  router:
    build: ./01_router
    container_name: router
    cap_add:
      - NET_ADMIN
    privileged: true
    networks:
      lan:
        ipv4_address: 10.10.10.20
    ports:
      - "80:80"     # HTTP
      - "443:443"   # HTTPS
      - "1053:1053/udp" # DNS
      - "1053:1053/tcp" # DNS
      - "25:25"     # SMTP
      - "587:587"   # Submission
      - "143:143"   # IMAP
      - "666/udp" # VPN / change
      - "1812:1812/udp" # RADIUS
      - "1813:1813/udp" # RADIUS accounting
      - "22:22"   # SSH
    restart: unless-stopped

  reverse-proxy:
    image: nginx
    container_name: reverse-proxy
    networks:
      lan:
        ipv4_address: 10.10.10.2
    volumes:
      - ./02_reverse-proxy/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./02_reverse-proxy/certs:/etc/nginx/certs:ro
    restart: unless-stopped


  dns:
    image: ubuntu/bind9:latest
    container_name: dns
    networks:
      lan:
        ipv4_address: 10.10.10.5
    volumes:
      - ./03_dns/bind/named.conf.options:/etc/bind/named.conf.options:ro
      - ./03_dns/bind/named.conf.local:/etc/bind/named.conf.local:ro
      - ./03_dns/bind/zones:/etc/bind/zones:ro
    restart: unless-stopped

  webserver:
    image: nginx
    container_name: webserver
    networks:
      lan:
        ipv4_address: 10.10.10.10
    restart: unless-stopped

  mailserver:
    image: mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: "mail"
    domainname: "mydomain.local"
    env_file:
      - ./04_mailserver/.env
    volumes:
      - ./04_mailserver/config/:/tmp/docker-mailserver/:rw
      - ./04_mailserver/maildata/:/var/mail/:rw
      - ./04_mailserver/state/:/var/mail-state/:rw
    networks:
      lan:
        ipv4_address: 10.10.10.15 
    restart: unless-stopped


  vpn:
    image: linuxserver/wireguard
    container_name: vpn
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Prague
      - SERVERURL=localhost 
      - SERVERPORT=666 # VARIABLE
      - PEERS=1                    
      - PEERDNS=10.10.10.5        
      - INTERNAL_SUBNET=10.200.200.0/24
    volumes:
      - ./06_vpn/config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv4.ip_forward=1
    networks:
      lan:
        ipv4_address: 10.10.10.30
    restart: unless-stopped

  aaa:
    image: freeradius/freeradius-server:latest
    container_name: aaa
    command: ["radiusd","-X"] # debug mode
    networks:
      lan:
        ipv4_address: 10.10.10.7
    volumes:
      - ./07_aaa/clients.conf:/etc/raddb/clients.conf:ro
      - ./07_aaa/users:/etc/raddb/mods-config/files/authorize:ro
    restart: unless-stopped

    

networks:
  lan:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
